In [34]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Data Preprocessing
data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data\\Entropy 120\\"
classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
X = []
y = []

for class_idx, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    for file_name in os.listdir(class_dir):
        if file_name.endswith('.xlsx'):
            file_path = os.path.join(class_dir, file_name)
            df = pd.read_excel(file_path)
            intensity_values = df['Intensity'].values
            entropy_0_values = df['Entropy 0'].values
            entropy_1_values = df['Entropy 1'].values
            features = np.column_stack((intensity_values, entropy_0_values, entropy_1_values))
            X.append(features)
            for i in range(len(features)):  
                y.append(class_idx)
X = np.concatenate(X)
y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=2)



In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=2)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print("Random Forest Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf)) 

import pickle

# Save the model to disk
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)


Random Forest Results:
[[5846 2955 1831]
 [2907 5743 1807]
 [1544 1659 7250]]
              precision    recall  f1-score   support

           0       0.57      0.55      0.56     10632
           1       0.55      0.55      0.55     10457
           2       0.67      0.69      0.68     10453

    accuracy                           0.60     31542
   macro avg       0.60      0.60      0.60     31542
weighted avg       0.60      0.60      0.60     31542



In [36]:
import xgboost as xgb

# Create and train the model
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes), random_state=2)
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
print("XGBoost Results:")

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
xgb_model.save_model('xgboost_model.model')


XGBoost Results:
[[5760 2961 1911]
 [3473 4795 2189]
 [1431 1464 7558]]
              precision    recall  f1-score   support

           0       0.54      0.54      0.54     10632
           1       0.52      0.46      0.49     10457
           2       0.65      0.72      0.68     10453

    accuracy                           0.57     31542
   macro avg       0.57      0.57      0.57     31542
weighted avg       0.57      0.57      0.57     31542



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:160: UserWarning: [11:10:05] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)


In [4]:
# svm_model = SVC(kernel='linear')
# svm_model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = svm_model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))


In [39]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Data Preprocessing
data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data\\Entropy 120\\"
classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
X = []
y = []

for class_idx, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    for file_name in os.listdir(class_dir):
        if file_name.endswith('.xlsx'):
            file_path = os.path.join(class_dir, file_name)
            df = pd.read_excel(file_path)
            # Aggregate features from the whole file
            intensity_values = df['Intensity'].mean()  # Mean intensity
            entropy_0_values = df['Entropy 0'].mean()  # Mean entropy 0
            entropy_1_values = df['Entropy 1'].mean()  # Mean entropy 1
            features = [intensity_values, entropy_0_values, entropy_1_values]
            X.append(features)
            y.append(class_idx)

X = np.array(X)
y = np.array(y)

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# # Step 2: Model Selection and Training
# svm_model = SVC(kernel='linear')
# svm_model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = svm_model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))


In [6]:

# import os
# import numpy as np
# import pandas as pd
# from sklearn.model_selection import train_test_split
# import xgboost as xgb
# from sklearn.metrics import classification_report, confusion_matrix

# # Step 1: Data Preprocessing
# data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data Old\\Entropy\\"
# classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
# X = []
# y = []

# for class_idx, class_name in enumerate(classes):
#     class_dir = os.path.join(data_dir, class_name)
#     for file_name in os.listdir(class_dir):
#         if file_name.endswith('.xlsx'):
#             file_path = os.path.join(class_dir, file_name)
#             df = pd.read_excel(file_path)
#             intensity_values = df['Intensity'].values
#             entropy_0_values = df['Entropy 0'].values
#             entropy_1_values = df['Entropy 1'].values
#             features = np.column_stack((intensity_values, entropy_0_values, entropy_1_values))
#             X.append(features)
#             for i in range(len(features)):  
#                 y.append(class_idx)


# X = np.concatenate(X)
# y = np.array(y)

# # Splitting data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Step 2: Model Selection and Training
# model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes))
# model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))
# xgb_model.save_model('xgboost_model.model')


In [7]:
!pip install xgboost


In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=2)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print("Random Forest Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf)) 

import pickle

# Save the model to disk
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)


Random Forest Results:
[[19  4  1]
 [ 7 18  2]
 [ 2  2 17]]
              precision    recall  f1-score   support

           0       0.68      0.79      0.73        24
           1       0.75      0.67      0.71        27
           2       0.85      0.81      0.83        21

    accuracy                           0.75        72
   macro avg       0.76      0.76      0.76        72
weighted avg       0.76      0.75      0.75        72



In [9]:
import xgboost as xgb

# Create and train the model
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes), random_state=42)
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
print("XGBoost Results:")

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
xgb_model.save_model('xgboost_model.model')


XGBoost Results:
[[31 14  2]
 [20 29  5]
 [ 1  1 41]]
              precision    recall  f1-score   support

           0       0.60      0.66      0.63        47
           1       0.66      0.54      0.59        54
           2       0.85      0.95      0.90        43

    accuracy                           0.70       144
   macro avg       0.70      0.72      0.71       144
weighted avg       0.70      0.70      0.70       144



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:160: UserWarning: [11:02:03] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)


In [10]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Data Preprocessing
data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data\\Entropy\\"
classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
X = []
y = []

for class_idx, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    for file_name in os.listdir(class_dir):
        if file_name.endswith('.xlsx'):
            file_path = os.path.join(class_dir, file_name)
            df = pd.read_excel(file_path)
            intensity_values = df['Intensity'].values
            entropy_0_values = df['Entropy 0'].values
            entropy_1_values = df['Entropy 1'].values
            features = np.column_stack((intensity_values, entropy_0_values, entropy_1_values))
            X.append(features)
            for i in range(len(features)):  
                y.append(class_idx)
X = np.concatenate(X)
y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=2)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print("Random Forest Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf)) 

import pickle

# Save the model to disk
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)


Random Forest Results:
[[662 125 111]
 [ 91 662  98]
 [ 55  71 755]]
              precision    recall  f1-score   support

           0       0.82      0.74      0.78       898
           1       0.77      0.78      0.77       851
           2       0.78      0.86      0.82       881

    accuracy                           0.79      2630
   macro avg       0.79      0.79      0.79      2630
weighted avg       0.79      0.79      0.79      2630



In [12]:
import xgboost as xgb

# Create and train the model
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes), random_state=42)
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
print("XGBoost Results:")

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
xgb_model.save_model('xgboost_model.model')


XGBoost Results:
[[644 139 115]
 [106 590 155]
 [ 39  63 779]]
              precision    recall  f1-score   support

           0       0.82      0.72      0.76       898
           1       0.74      0.69      0.72       851
           2       0.74      0.88      0.81       881

    accuracy                           0.77      2630
   macro avg       0.77      0.76      0.76      2630
weighted avg       0.77      0.77      0.76      2630



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:160: UserWarning: [11:02:06] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)


In [13]:
# svm_model = SVC(kernel='linear')
# svm_model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = svm_model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))


In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Data Preprocessing
data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data\\Entropy\\"
classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
X = []
y = []

for class_idx, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    for file_name in os.listdir(class_dir):
        if file_name.endswith('.xlsx'):
            file_path = os.path.join(class_dir, file_name)
            df = pd.read_excel(file_path)
            # Aggregate features from the whole file
            intensity_values = df['Intensity'].mean()  # Mean intensity
            entropy_0_values = df['Entropy 0'].mean()  # Mean entropy 0
            entropy_1_values = df['Entropy 1'].mean()  # Mean entropy 1
            features = [intensity_values, entropy_0_values, entropy_1_values]
            X.append(features)
            y.append(class_idx)

X = np.array(X)
y = np.array(y)

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=2)

# # Step 2: Model Selection and Training
# svm_model = SVC(kernel='linear')
# svm_model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = svm_model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))


In [2]:

# import os
# import numpy as np
# import pandas as pd
# from sklearn.model_selection import train_test_split
# import xgboost as xgb
# from sklearn.metrics import classification_report, confusion_matrix

# # Step 1: Data Preprocessing
# data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data Old\\Entropy\\"
# classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
# X = []
# y = []

# for class_idx, class_name in enumerate(classes):
#     class_dir = os.path.join(data_dir, class_name)
#     for file_name in os.listdir(class_dir):
#         if file_name.endswith('.xlsx'):
#             file_path = os.path.join(class_dir, file_name)
#             df = pd.read_excel(file_path)
#             intensity_values = df['Intensity'].values
#             entropy_0_values = df['Entropy 0'].values
#             entropy_1_values = df['Entropy 1'].values
#             features = np.column_stack((intensity_values, entropy_0_values, entropy_1_values))
#             X.append(features)
#             for i in range(len(features)):  
#                 y.append(class_idx)


# X = np.concatenate(X)
# y = np.array(y)

# # Splitting data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Step 2: Model Selection and Training
# model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes))
# model.fit(X_train, y_train)

# # Step 3: Evaluation
# y_pred = model.predict(X_test)
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred, target_names=classes))
# xgb_model.save_model('xgboost_model.model')


In [3]:
!pip install xgboost


In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=2)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print("Random Forest Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf)) 

import pickle

# Save the model to disk
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)


Random Forest Results:
[[4 0 2]
 [0 8 0]
 [0 1 9]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         6
           1       0.89      1.00      0.94         8
           2       0.82      0.90      0.86        10

    accuracy                           0.88        24
   macro avg       0.90      0.86      0.87        24
weighted avg       0.89      0.88      0.87        24



In [5]:
import xgboost as xgb

# Create and train the model
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes), random_state=2)
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
print("XGBoost Results:")

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
xgb_model.save_model('xgboost_model.model')


XGBoost Results:
[[5 0 1]
 [0 8 0]
 [2 0 8]]
              precision    recall  f1-score   support

           0       0.71      0.83      0.77         6
           1       1.00      1.00      1.00         8
           2       0.89      0.80      0.84        10

    accuracy                           0.88        24
   macro avg       0.87      0.88      0.87        24
weighted avg       0.88      0.88      0.88        24



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:160: UserWarning: [15:24:17] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)


In [24]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Step 3: Evaluation
y_pred = svm_model.predict(X_test)
print("SVM Results:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=classes))

SVM Results:
Confusion Matrix:
[[ 93   0  19]
 [ 40   3   5]
 [ 42   0 141]]

Classification Report:
                 precision    recall  f1-score   support

   Normal cases       0.53      0.83      0.65       112
   Bengin cases       1.00      0.06      0.12        48
Malignant cases       0.85      0.77      0.81       183

       accuracy                           0.69       343
      macro avg       0.80      0.55      0.53       343
   weighted avg       0.77      0.69      0.66       343



In [19]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Data Preprocessing
data_dir = "C:\\Users\\Aneesh PB\\Downloads\\Topology Project\\New Data\\Entropy All Images\\"
classes = ['Normal cases', 'Bengin cases', 'Malignant cases']
X = []
y = []

for class_idx, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    for file_name in os.listdir(class_dir):
        if file_name.endswith('.xlsx'):
            file_path = os.path.join(class_dir, file_name)
            df = pd.read_excel(file_path)
            # Aggregate features from the whole file
            intensity_values = df['Intensity'].mean()  # Mean intensity
            entropy_0_values = df['Entropy 0'].mean()  # Mean entropy 0
            entropy_1_values = df['Entropy 1'].mean()  # Mean entropy 1
            features = [intensity_values, entropy_0_values, entropy_1_values]
            X.append(features)
            y.append(class_idx)

X = np.array(X)
y = np.array(y)

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=2)


import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

# Define the model
nn_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(len(classes), activation='softmax')
])

# Compile the model
nn_model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
nn_model.fit(X_train, y_train, epochs=100, batch_size=4, validation_data=(X_test, y_test))

# Evaluate the model
y_pred_nn = np.argmax(nn_model.predict(X_test), axis=-1)
print("Neural Network Results:")
print(confusion_matrix(y_test, y_pred_nn))
print(classification_report(y_test, y_pred_nn))
#nn_model.save('nn_model')


Epoch 1/100


c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


129/129 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3643 - loss: 2.2458 - val_accuracy: 0.1399 - val_loss: 1.9906
Epoch 2/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3772 - loss: 1.6686 - val_accuracy: 0.5335 - val_loss: 1.1820
Epoch 3/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4432 - loss: 1.2144 - val_accuracy: 0.3265 - val_loss: 1.4681
Epoch 4/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4217 - loss: 1.1879 - val_accuracy: 0.3265 - val_loss: 1.5952
Epoch 5/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4452 - loss: 1.3999 - val_accuracy: 0.5335 - val_loss: 1.6416
Epoch 6/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4622 - loss: 1.3704 - val_accuracy: 0.3265 - val_loss: 1.4532
Epoch 7/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5202 - loss: 1.1535 - val_accuracy: 0.1399 - val_loss: 1.3709
Epoch 8/100
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3942 - loss: 1.1545 - val_accuracy: 0.5335

c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_

In [20]:
print("Neural Network Results:")
print(confusion_matrix(y_test, y_pred_nn))
print(classification_report(y_test, y_pred_nn))
#nn_model.save('nn_model')


Neural Network Results:
[[ 43   0  69]
 [ 18   0  30]
 [  0   0 183]]
              precision    recall  f1-score   support

           0       0.70      0.38      0.50       112
           1       0.00      0.00      0.00        48
           2       0.65      1.00      0.79       183

    accuracy                           0.66       343
   macro avg       0.45      0.46      0.43       343
weighted avg       0.58      0.66      0.58       343



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pickle

# Create and train the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors (k)
knn_model.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
print("KNN Results:")
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn)) 

# Save the model to disk
with open('knn_model.pkl', 'wb') as f:
    pickle.dump(knn_model, f)


KNN Results:
[[ 80   9  23]
 [ 19  21   8]
 [ 21  13 149]]
              precision    recall  f1-score   support

           0       0.67      0.71      0.69       112
           1       0.49      0.44      0.46        48
           2       0.83      0.81      0.82       183

    accuracy                           0.73       343
   macro avg       0.66      0.66      0.66       343
weighted avg       0.73      0.73      0.73       343



In [22]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
import pickle

# Create and train the Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Make predictions
y_pred_nb = nb_model.predict(X_test)

# Evaluate the model
print("Naive Bayes Results:")
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb)) 

# Save the model to disk
with open('naive_bayes_model.pkl', 'wb') as f:
    pickle.dump(nb_model, f)


Naive Bayes Results:
[[112   0   0]
 [ 45   3   0]
 [150   0  33]]
              precision    recall  f1-score   support

           0       0.36      1.00      0.53       112
           1       1.00      0.06      0.12        48
           2       1.00      0.18      0.31       183

    accuracy                           0.43       343
   macro avg       0.79      0.41      0.32       343
weighted avg       0.79      0.43      0.35       343



In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pickle

# Create and train the logistic regression model
log_reg_model = LogisticRegression(random_state=2)
log_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_lr = log_reg_model.predict(X_test)

# Evaluate the model
print("Logistic Regression Results:")
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr)) 

# Save the model to disk
with open('logistic_regression_model.pkl', 'wb') as f:
    pickle.dump(log_reg_model, f)


Logistic Regression Results:
[[ 79   0  33]
 [ 40   0   8]
 [ 34   0 149]]
              precision    recall  f1-score   support

           0       0.52      0.71      0.60       112
           1       0.00      0.00      0.00        48
           2       0.78      0.81      0.80       183

    accuracy                           0.66       343
   macro avg       0.43      0.51      0.47       343
weighted avg       0.59      0.66      0.62       343



c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Aneesh PB\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classific

In [7]:
# from sklearn.svm import SVC

# # Create and train the model
# svm_model = SVC(kernel='linear', C=1.0, random_state=42)
# svm_model.fit(X_train, y_train)

# # Make predictions
# y_pred_svm = svm_model.predict(X_test)

# # Evaluate the model
# print("SVM Results:")
# print(confusion_matrix(y_test, y_pred_svm))
# print(classification_report(y_test, y_pred_svm))
# from joblib import dump, load

# # Save the model to disk
# dump(svm_model, 'svm_model.joblib')



In [8]:
# rbf = SVC(kernel='rbf', gamma=0.5, C=0.1).fit(X_train, y_train)
# poly = SVC(kernel='poly', degree=3, C=1).fit(X_train, y_train)

# y_pred_svm_rbf = rbf.predict(X_test)

# # Evaluate the model
# print("SVM Results:")
# print(confusion_matrix(y_test, y_pred_svm_rbf))
# print(classification_report(y_test, y_pred_svm_rbf))
# from joblib import dump, load

# # Save the model to disk
# dump(svm_model, 'svm_model_rbf.joblib')

# y_pred_svm_poly = poly.predict(X_test)

# # Evaluate the model
# print("SVM Results:")
# print(confusion_matrix(y_test, y_pred_svm_poly))
# print(classification_report(y_test, y_pred_svm_poly))
# from joblib import dump, load

# # Save the model to disk
# dump(svm_model, 'svm_model.joblib')

In [10]:
# #import tensorflow as tf
# from keras.models import Sequential
# from keras.layers import Dense

# # Define the model
# nn_model = Sequential([
#     Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
#     Dense(64, activation='relu'),
#     Dense(len(classes), activation='softmax')
# ])

# # Compile the model
# nn_model.compile(optimizer='adam',
#               loss='sparse_categorical_crossentropy',
#               metrics=['accuracy'])

# # Train the model
# nn_model.fit(X_train, y_train, epochs=1000, batch_size=16, validation_data=(X_test, y_test))

# # Evaluate the model
# y_pred_nn = np.argmax(nn_model.predict(X_test), axis=-1)
# print("Neural Network Results:")
# print(confusion_matrix(y_test, y_pred_nn))
# print(classification_report(y_test, y_pred_nn))
# nn_model.save('nn_model.keras')


In [11]:
# from sklearn.ensemble import VotingClassifier

# # Create individual classifiers
# rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
# xgb_classifier = xgb.XGBClassifier(objective='multi:softmax', num_class=len(classes), random_state=42)
# svm_classifier = SVC(kernel='linear', C=1.0, probability=True, random_state=42)

# # Create a voting classifier
# voting_clf = VotingClassifier(estimators=[
#     ('random_forest', rf_classifier),
#     ('xgboost', xgb_classifier),
#     ('svm', svm_classifier)
# ], voting='soft') # 'soft' voting for probabilities

# # Train the voting classifier
# voting_clf.fit(X_train, y_train)

# # Make predictions
# y_pred_voting = voting_clf.predict(X_test)

# # Evaluate the model
# print("Voting Classifier Results:")
# print(confusion_matrix(y_test, y_pred_voting))
# print(classification_report(y_test, y_pred_voting))

# with open('random_forest_model1.pkl', 'wb') as f:
#     pickle.dump(rf_classifier, f)

# xgb_classifier.save_model('xgboost_model1.model')

# dump(svm_classifier, 'svm_model1.joblib')


In [12]:
# from xgboost import XGBClassifier
# from sklearn.model_selection import GridSearchCV, train_test_split
# from sklearn.metrics import mean_squared_error, accuracy_score

# # Data Preparation
# # X = df['Intensity']
# # y = df[['Entropy 0', 'Entropy 1']]
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define the XGBoost classifier
# clf = XGBClassifier()

# # Define the parameter grid to search
# param_grid = {
#     'n_estimators': [50, 100, 150, 200, 250, 300, 350, 400, 450, 500],
#     'max_depth': [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
#     'learning_rate': [0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45],
#     'min_child_weight': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
#     'gamma': [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
#     'subsample': [0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
#     'colsample_bytree': [0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
#     'reg_alpha': [0, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0],
#     'reg_lambda': [0, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0]
# }

# # Perform grid search
# grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring='accuracy')
# grid_search.fit(X_train, y_train)

# # Print the best parameters found
# print("Best parameters:", grid_search.best_params_)

# # Predict on the test set using the best model
# best_clf = grid_search.best_estimator_
# y_pred = best_clf.predict(X_test)

# # Calculate accuracy

# # Best Parameters
# # best_params = grid_search.best_params_

# # # Model Training
# # best_model = XGBRegressor(**best_params)
# # best_model.fit(X_train, y_train)

# # # Model Evaluation



In [13]:
# import pandas as pd
# import xgboost as xgb
# from sklearn.model_selection import GridSearchCV, train_test_split
# from sklearn.metrics import accuracy_score


# # Split data into training and testing sets
# # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define the XGBoost classifier
# clf = xgb.XGBClassifier()

# # Define the parameter grid to search
# param_grid = {
#     'n_estimators': [100, 200, 300, 400],
#     'max_depth': [3, 5, 7, 9],
#     'learning_rate': [0.05, 0.1, 0.2],
#     'min_child_weight': [1, 3, 5, 7],
#     'gamma': [0, 0.1, 0.2, 0.3],
#     'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
#     'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
#     'reg_alpha': [0, 0.1, 0.5, 1.0],
#     'reg_lambda': [0, 0.1, 0.5, 1.0]
# }

# # Perform grid search
# grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring='accuracy')
# grid_search.fit(X_train, y_train)

# # Print the best parameters found
# print("Best parameters:", grid_search.best_params_)

# # Predict on the test set using the best model
# best_clf = grid_search.best_estimator_
# y_pred = best_clf.predict(X_test)

# # Calculate accuracy
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)


In [14]:
# param_grid = {
#     'n_estimators': [100, 200, 300, 400, 500],
#     'max_depth': [3, 5, 7, 9, 11],
#     'learning_rate': [0.01, 0.1, 0.2, 0.3, 0.4],
#     'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
#     'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
#     'gamma': [0.0, 0.1, 0.2, 0.3, 0.4],
#     'min_child_weight': [1, 3, 5, 7, 9],
#     'reg_alpha': [0.0, 0.1, 0.2, 0.3, 0.4],
#     'reg_lambda': [0.0, 0.1, 0.2, 0.3, 0.4],
#     #'scale_pos_weight': [1, 2, 3, 4, 5]
# }

# # Perform grid search
# grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring='accuracy')
# grid_search.fit(X_train, y_train)

# # Print the best parameters found
# print("Best parameters:", grid_search.best_params_)

# # Predict on the test set using the best model
# best_clf = grid_search.best_estimator_
# y_pred = best_clf.predict(X_test)

# # Calculate accuracy
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)

In [15]:
# # mse = mean_squared_error(y_test, best_model.predict(X_test))
# # print("Mean Squared Error:", mse)

# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)
# # Make predictions
# y_pred_xgb = clf.predict(X_test)

# # Evaluate the model
# print("XGBoost Results:")

# print(confusion_matrix(y_test, y_pred_xgb))
# clf.save_model('xgboost_gridsearch_model.model')

In [16]:

# # Load individual models
# with open('random_forest_model.pkl', 'rb') as f:
#     loaded_rf_classifier = pickle.load(f)

# loaded_xgb_classifier = xgb.XGBClassifier()
# loaded_xgb_classifier.load_model('xgboost_model.model')

# loaded_svm_classifier = load('svm_model.joblib')

# # Create a new VotingClassifier with loaded models
# loaded_voting_clf = VotingClassifier(estimators=[
#     ('random_forest', loaded_rf_classifier),
#     ('xgboost', loaded_xgb_classifier),
#     ('svm', loaded_svm_classifier)
# ], voting='soft')

# # Make predictions using the loaded voting classifier
# y_pred_loaded_voting = loaded_voting_clf.predict(X_test)